--- Makefile.orig	Mon Sep  6 23:51:38 2010
+++ Makefile	Thu Sep  9 21:15:52 2010
@@ -189,6 +189,7 @@
 SIM_RUN_OBJS = nrun.o
 
 SIM_OBJS = compile.o \
+	   device.o \
 	   $(SIM_NEW_COMMON_OBJS) \
 	   sim-cpu.o \
 	   sim-engine.o \
